# Generated by Django 5.2.6 on 2025-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(help_text='Car name', max_length=255)),
                ('Model', models.CharField(help_text='Model', max_length=255)),
                ('Colour', models.CharField(help_text='Colour', max_length=255)),
            ],
        ),
    ]
